"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab

from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = os.path.join(BASE_DIR, '.env')
load_dotenv(ENV_PATH)


def _read_key_file(path: Path) -> str:
    if not path.exists():
        return ''
    return path.read_text(encoding='utf-8')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+=&%3@*#5$dll72ay_frm=f7-p$jddaek^)6cw59j@t2$zoqpp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_otp',
    'django_otp_webauthn',
    'apps.blockchain',
    'apps.users',
    'apps.auths',
]
CORS_ALLOW_ALL_ORIGINS = True
AUTH_USER_MODEL = 'users.User'

JWT_PRIVATE_KEY_PATH = Path(os.getenv('JWT_PRIVATE_KEY_PATH', BASE_DIR / 'keys' / 'private_key.pem'))
JWT_PUBLIC_KEY_PATH = Path(os.getenv('JWT_PUBLIC_KEY_PATH', BASE_DIR / 'keys' / 'public_key.pem'))
JWT_PRIVATE_KEY = _read_key_file(JWT_PRIVATE_KEY_PATH)
JWT_PUBLIC_KEY = _read_key_file(JWT_PUBLIC_KEY_PATH)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# AUTHENTICATION_BACKENDS = [
#     "django.contrib.auth.backends.ModelBackend",
#     "django_otp_webauthn.backends.WebAuthnBackend",
# ]
ROOT_URLCONF = 'core.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ALGORITHM': 'RS256' if JWT_PRIVATE_KEY and JWT_PUBLIC_KEY else 'HS256',
    'SIGNING_KEY': JWT_PRIVATE_KEY or SECRET_KEY,
    'VERIFYING_KEY': JWT_PUBLIC_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'charity'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        # If DB_HOST isn't in .env, leaving it completely out or setting to None
        # forces Postgres to use local Unix sockets (fixing the test crash!)
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=charity_app,public'
        },
        'TEST': {
            'NAME': 'test_charity_app'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# email settings
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') or os.getenv('EMAIN_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or f'Charity App <{EMAIL_HOST_USER or "no-reply@localhost"}>'

DEFAULT_EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', DEFAULT_EMAIL_BACKEND)

# webauthn settings
OTP_WEBAUTHN_RP_ID = os.environ.get('WEBAUTHN_RP_ID') or 'localhost'
OTP_WEBAUTHN_RP_NAME = "Charity App"
OTP_WEBAUTHN_ALLOWED_ORIGINS = ["http://localhost:3000"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# Blockchain settings
WEB3_PROVIDER_URL = os.getenv('WEB3_PROVIDER_URL', 'http://localhost:8545')
WEB3_WEBSOCKET_URL = os.getenv('WEB3_WEBSOCKET_URL', 'ws://localhost:8545')
BLOCK_TRACKER_RANGE = int(os.getenv('BLOCK_TRACKER_RANGE', '100'))
USER_REGISTRAR_CONTRACT_ADDRESS = os.getenv('USER_REGISTRAR_CONTRACT_ADDRESS')
REPUTATION_CURVE_EXPONENT = 2
# GCP cloud vision settings
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.path.join(BASE_DIR, "gcloud-key.json")


# Celery settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_BEAT_SCHEDULE = {
    'momentum-promotion-daily': {
        'task': 'jobs.tasks.run_momentum_promotion_task',
        'schedule': crontab(hour=0, minute=0),  # midnight every day
    },
    'random-promotion-daily': {
        'task': 'jobs.tasks.run_random_promotion_task',
        'schedule': crontab(hour=0, minute=30),  # 00:30
    },
    'sync-score-events-periodic': {
        'task': 'apps.reputation.tasks.sync_score_events_task',
        'schedule': 60.0,
    },
    'blockchain-polling-periodic': {
        'task': 'apps.blockchain.tasks.run_polling_listener_task',
        'schedule': 60.0,
    },
    'blockchain-websocket-listener': {
        'task': 'apps.blockchain.tasks.run_websocket_listener_task',
        'schedule': 60.0, # This will just ensure it's running if it somehow stops
    }
}

