# Generated by Django 6.0.6 on 2026-06-18 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('religious', 'Religious certificate'), ('tax', 'Tax document'), ('other', 'Other document')], max_length=255)),
                ('image', models.ImageField(upload_to='doc_reviews/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=255)),
                ('ai_extracted', models.JSONField(blank=True, default=dict)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_docs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=255, null=True)),
                ('region_country', models.CharField(blank=True, max_length=255, null=True)),
                ('region_state', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField()),
                ('device_name', models.CharField(default='My Device', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
